version: '3.7'

services:
  formazione-cfp:
    container_name: formazione-cfp
    build: .
    restart: always
    volumes:
      - /storage/netcore_app/formazione-cfp:/app
    networks:
      - lan-network
    ports:
      - 5006:5006

networks:
  lan-network:
    external:
      name: docker-lan
