version: '3.7'

services:
  app_formazione-cfp:
    container_name: app_formazione-cfp
    build: .
    restart: always
    volumes:
      - /gestioneCFP/storage/app:/app
    networks:
      - lan-network
    ports:
      - 5006:5006

networks:
  lan-network:
    external:
      name: docker-lan