version: '3.7'

services:
  db_formazione-cfp:
    container_name: db_formazione-cfp
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=PASSWORD-SQLSERVER
      - MSSQL_PID=Express
    networks:
      - lan-network
    volumes:
      - /gestioneCFP/storage/database/data:/var/opt/mssql/data
    ports:
      - 1433:1433

networks:
  lan-network:
    external:
      name: docker-lan